version: "3"
services:
  app:
    container_name: app
    restart: always
    image: mashhad65/accountmanagement
    ports:
      - "4000:4000"
    # depends_on:
    #   - auth
    #   - mongo2
    #   - mongo
    networks:
      - mynet
  authentiq-db:
    container_name: db
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - mynet
  mongo:
    container_name: account_db
    image: mongo
    ports:
      - "27018:27017"
    networks:
      - mynet
  auth:
    container_name: auth
    image: sayid/authentiq
    ports:
      - "2000:2000"
    networks:
      - mynet

networks:
  mynet:
