version: "2"
services:
  app:
    container_name: app
    restart: always
    image: reza
    ports:
      - "4000:4000"
    links:
      - mongo
      - auth
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
  auth:
    container_name: auth
    image: sayid/auth
    ports:
      - "2000:2000"
